USE [master]
GO

/****** Object:  Database [BisselCentre]    Script Date: 2019-09-09 11:59:00 PM ******/
CREATE DATABASE [BisselCentre]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BisselCentre', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BisselCentre.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BisselCentre_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BisselCentre_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BisselCentre] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BisselCentre].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BisselCentre] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BisselCentre] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BisselCentre] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BisselCentre] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BisselCentre] SET ARITHABORT OFF 
GO

ALTER DATABASE [BisselCentre] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BisselCentre] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BisselCentre] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BisselCentre] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BisselCentre] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BisselCentre] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BisselCentre] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BisselCentre] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BisselCentre] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BisselCentre] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BisselCentre] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BisselCentre] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BisselCentre] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BisselCentre] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BisselCentre] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BisselCentre] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BisselCentre] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BisselCentre] SET RECOVERY FULL 
GO

ALTER DATABASE [BisselCentre] SET  MULTI_USER 
GO

ALTER DATABASE [BisselCentre] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BisselCentre] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BisselCentre] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BisselCentre] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BisselCentre] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BisselCentre] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BisselCentre] SET  READ_WRITE 
GO

